name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v2

#       - name: Build
#         run: npm i && npm run build

      - name: Clone website repo
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          owner: bener-fork
          repository: hello-nav.github.io
          access-token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Deploy
        run: |
          ls
          sudo chown -R $USER:$USER ./hello-nav.github.io
          cd hello-nav.github.io
          ls
          rm -rf ./*
          ls
          git config --global user.name
          git config --global user.email
          git add .
          git commit -m "CI BUILD"
          git push origin master
